[package]
name = "cfg_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
serde = {version = "1",features = ["derive"]}
serde_yaml = "0.9"
syn = {version = "2.0",features = ["derive"]}
quote = "1.0"
proc-macro2 = "1.0"
cfg_lib = {path = "../cfg_lib"}